"""First

Revision ID: 40ddd7b92c8d
Revises: 7288f03b484a
Create Date: 2022-01-02 22:07:47.495263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ddd7b92c8d'
down_revision = '7288f03b484a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
